"""initial schema

Revision ID: d02ec6cd14f2
Revises: 
Create Date: 2026-07-04 12:32:33.142878
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = 'd02ec6cd14f2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suite_version', sa.String(length=40), nullable=False),
    sa.Column('git_sha', sa.String(length=40), nullable=True),
    sa.Column('exec_accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('valid_sql_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('intent_accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_request_id'), ['request_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ask_request',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('sem_version', sa.Integer(), nullable=False),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ask_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ask_request_project_id'), ['project_id'], unique=False)

    op.create_table('data_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('config_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_project_id'), ['project_id'], unique=False)

    op.create_table('eval_case_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.String(length=80), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('generated_sql', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['eval_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_case_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_case_result_run_id'), ['run_id'], unique=False)

    op.create_table('query_cache',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_hash')
    )
    with op.batch_alter_table('query_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_cache_project_id'), ['project_id'], unique=False)

    op.create_table('semantic_layer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version')
    )
    with op.batch_alter_table('semantic_layer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_semantic_layer_project_id'), ['project_id'], unique=False)

    op.create_table('dashboard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ask_request_id', sa.Uuid(), nullable=False),
    sa.Column('layout', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('charts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['ask_request_id'], ['ask_request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_ask_request_id'), ['ask_request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboard', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_ask_request_id'))

    op.drop_table('dashboard')
    with op.batch_alter_table('semantic_layer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_semantic_layer_project_id'))

    op.drop_table('semantic_layer')
    with op.batch_alter_table('query_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_cache_project_id'))

    op.drop_table('query_cache')
    with op.batch_alter_table('eval_case_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_case_result_run_id'))

    op.drop_table('eval_case_result')
    with op.batch_alter_table('data_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_project_id'))

    op.drop_table('data_source')
    with op.batch_alter_table('ask_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ask_request_project_id'))

    op.drop_table('ask_request')
    op.drop_table('project')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_request_id'))

    op.drop_table('llm_usage')
    op.drop_table('eval_run')
    # ### end Alembic commands ###
